// <auto-generated />
namespace ForexTrading.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RowUpdates050714 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RowUpdates050714));
        
        string IMigrationMetadata.Id
        {
            get { return "201405071926166_RowUpdates050714"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
